### PR TITLE
[BUGFIX] Migrate from deprecated utf8_encode()

### LINKED ISSUE #116: Bug: Php deprecation utf8_encode
The method utf8_encode() is deprecated since php 8.2.
This can lead to a PHP Runtime Deprecation Notice, which could lead to an exception in TYPO3 depending on the seconds.

### PR DESCRIPTION
**Pull request by BastiLu**
For more information see: https://www.php.net/utf8_encode

Fixes #116

### CODE REVIEW

File: Classes/Utility/ImageUtility.php [hunk 1]
```diff
@@ -259,13 +259,17 @@ protected static function getBasicMetadata(string $fileName): array
...
     protected static function safeUtf8Encode(?string $text): ?string
     {
+        if (function_exists('mb_convert_encoding') === false) {
+            return $text;
+        }
+
         if (function_exists('mb_detect_encoding')) {
             if (mb_detect_encoding($text, 'UTF-8', true) !== 'UTF-8') {
-                $text = utf8_encode($text);
+                $text = mb_convert_encoding($text, 'UTF-8', 'ISO-8859-1');
```
Comment (xperseguers) [inline Classes/Utility/ImageUtility.php:268]: I (partly) agree with that very part, the rest is imho incorrect tu properly support various configurations.

IMHO best would simply to copy over what I wrote in another extension of mine for the very same conversion function:

https://github.com/xperseguers/t3ext-extractor/blob/master/Classes/Service/Php/PhpService.php#L625-L640

File: Classes/Utility/ImageUtility.php [hunk 2]
```diff
@@ -259,13 +259,17 @@ protected static function getBasicMetadata(string $fileName): array
      */
     protected static function safeUtf8Encode(?string $text): ?string
     {
+        if (function_exists('mb_convert_encoding') === false) {
```
Comment (xperseguers) [inline Classes/Utility/ImageUtility.php:262]: the whole point of that method is to support some "legacy" if `mb_convert_encoding` respectively `mb_detect_encoding` which is part of the same module is not available. Thus returning right away makes no sense.

**Review by xperseguers — APPROVED** [review]
